name: Machinekit
highlighter: pygments
permalink: blog/:year/:month/:day/:title/
markdown: kramdown
repository: https://github.com/machinekit/machinekit

gems:
  - jekyll-asciidoc
  - asciidoctor-diagram
  - pygments.rb

asciidoc: asciidoctor
asciidoc_ext: adoc,ad

asciidoctor:
  safe: 0
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style
